# pre-commit-config.yaml
# Please read https://pre-commit.com/ for more details

# Default pre-commit-hook to check newline at EOF
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

# Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
      - id: ruff-format
# FIXME: precommit strips the new line even if I add it manually. Problem is
# that `end-of-file-fixer` hook has been included already
